export const ErrorCode = {
  // Common
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS: 'USER_PHONE_ALREADY_EXISTS',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  //Role
  INVALID_ROLE_ADMIN: 'INVALID_ROLE_ADMIN',

  // Authorization
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_CODE_ALREADY_EXISTS: 'ROLE_CODE_ALREADY_EXISTS',
  INVALID_PERMISSION_IDS: 'INVALID_PERMISSION_IDS',
  INVALID_ROLE_IDS: 'INVALID_ROLE_IDS',
  SYSTEM_ROLE_IMMUTABLE: 'SYSTEM_ROLE_IMMUTABLE',

  // Customer
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_ALREADY_EXISTS: 'CUSTOMER_PHONE_ALREADY_EXISTS',

  // Product
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_ALREADY_EXISTS: 'PRODUCT_SKU_ALREADY_EXISTS',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',

  // Inventory
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',

  // Payment
  PAYMENT_ALREADY_PAID: 'PAYMENT_ALREADY_PAID',
} as const;
